### PR TITLE
use partially applied terms and formulas

### PR DESCRIPTION
**Pull request by fpvandoorn**
This is the idea with partially applied terms I mentioned today.

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Also, I changed the semantics of substitution: if you substitute `t` for `var n`, all variables above level `n` are reduced by 1. In my type theory formalization that was necessary to formulate the following rule:

`Γ, x : A, Δ ⊢ t : T` and `Γ ⊢ a : A` implies `Γ, Δ[a/x] ⊢ t[a/x] : T[a/x]`
(in that formalization, the lowest free variable corresponds to the last term in context, etc.)

I don't know if this is necessary to do in first-order logic.

**Comment by AlmostNever** [comment]
I think the substitution rule is moot in FOL... nothing is interestingly typed, right? 

The substitution semantics conflict with a shortcut I'm using right now for model theory, but I'm on the fence about it:
`var n 1` corresponds to the function `λx.λy.y`, or projection onto the second component.

**Comment by fpvandoorn** [comment]
The substitution rule above is indeed not necessary, but you still want the following simpler substitution rule: if `Γ ⊢ φ` then `Γ[t/x] ⊢ φ[t/x]`.
I don't know whether it will matter for you how the free variables are ordered. If you don't subtract by 1, there is one variable that you don't use at all, but maybe that will not matter at all for you.

It's probably good to stick with the easier definition for now, and see if that leads to any problems.

**Comment by flypitch** [comment]
Thanks, Floris!

We indeed need a rule which says we can instantiate a universally quantified statement at a closed term of the correct arity.

**Comment by fpvandoorn** [comment]
Yes, good point. 

I think you do want to use the semantics of substitution I suggested here (i.e. all variables above the substituted variable should be reduced by 1).
Suppose you want to prove that if `∀x, ∀y, φ` holds, then `∀x, φ[t/y]` holds (with `x ∉ FV(t)`). If you do that with de Bruijn variables, you will want to make sure that all occurrences `var 1` in `φ` become `var 0`, to be captured by the quantifier.

**Pull request merged**
